### ISSUE TITLE
Performance problems on Windows when scrolling

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#1]
If you:
* use Windows
* and have a emoji set other than "native emojis" selected

Then the performance when scrolling may be bad.

### Questions

* Can you confirm that?
* Any solution/potential problem?

Note: If you manually go to `moz-extension://<extension-id>/popup/index.html` ([access the extension id by going to `about:debugging` and clicking on "Manifest URL"](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#getting-started)) scrolling still works as expected. This only happens in the popup itself.

**Comment by rugk** [comment]
I am also interested in the experience with other OSes.

Because it does work fine on Linux/GNOME. 😃

**Comment by Prometheos2** [comment]
## Windows 8.1 - Firefox Developer 67.0b11 (64 bits)

I don't have issues while scrolling or changing tab, I only have a slight lag (<2s) when opening the toolbox; but I remember it was the same with a similar project.

**Comment by rugk** [comment]
Okay, strange, thanks FYI, however. Good to know that it does not appear there (did you also test the other emoji sets?).

**Comment by Prometheos2** [comment]
You mean to try that problem with the other sets, or just taking a look at other sets?

**Comment by rugk** [comment]
The first: Just whether it works with the other sets too… :smiley:

**Comment by Prometheos2** [comment]
It works with every set, yes

**Comment by rugk** [comment]
Also cannot reproduce anymore. Seems fixed.
