### ISSUE TITLE
Options (dropdown etc.) need to be clicked further down than where they are shown

### ISSUE THREAD

**Issue by GrosBourrin** [rugk/awesome-emoji-picker#115]
## Bug description
menus and clicking are not in the right place, few pixels down the right spot

## Steps to reproduce
click a few centimeters under the menu it opens as on the video there : 
<https://gyazo.com/52564a3387c154733984857bcf12fe56>
same for checkboxes  and horizontal slider

## System
windows 10 last version x64 - french language
Firefox 88.0.1 x64 french language
Version 2.0 of the extension
Dark mode

**Comment by rugk** [comment]
Thanks for the report!

I have some questions about the issue…

> Dark mode

Does it only apply in dark mode? If you change the mode, does it still work?

> same for checkboxes and horizontal slider

You mean you also have to click somewhere else (below) to get them work?

Adding a screenshot from the video:
![grafik](https://user-images.githubusercontent.com/11966684/119986528-3ba38700-bfc4-11eb-8b2a-9ba723625634.png)

—

Also, could you go [to `about:debugging`](https://extensionworkshop.com/documentation/develop/debugging/) and [have a look at the options page](https://extensionworkshop.com/documentation/develop/debugging/#debugging-options-pages)?

You can then use the select tool there to select the DropDown, e.g.:

![grafik](https://user-images.githubusercontent.com/11966684/119986969-c84e4500-bfc4-11eb-9891-8d5d878ca385.png)

If you did so, do you see anything extraordinary?
E.g. is the box there also at the wrong position? (A screenshot would be very helpful.)

I personally also tried to reproduce the issue with Firefox 88.0.1 on a Windows 10 system just now and could not do so. It certainly looks strange for you, though.

**Comment by GrosBourrin** [comment]
i have found the issue in my userChrome.css ! there was a conflict with some menu tweaks, sorry for disturbing you with nothing that was about your extension

**Comment by rugk** [comment]
Thanks. Anyway, it’s good you could fix it.

Happy time further using the add-on. :smiley: 

You can find more information on how to support this project, here: https://github.com/rugk/awesome-emoji-picker/blob/master/CONTRIBUTING.md#support-us
