### ISSUE TITLE
add twemoji support to awesome emoji picker

### ISSUE THREAD

**Issue by RandomPenguin1778** [rugk/awesome-emoji-picker#118]
Hi rugk !

Awesome emoji picker is a wonderful application ! i use it all the time . but can you add twemoji support to awesome emoji keyboard ? and please also add a feature where you can switch emoji fonts . 

Sincerely, 
RandomPenguin1778

**Comment by rugk** [comment]
It is already supported.

Open the settings of the add-on (if you don't know how: right-click on the toolbar button and choose “Manage extension”, then click on “Settings”).
There just choose “Twitter” as the emoji style, which is [Tweemoji](https://twemoji.twitter.com/). 

![image](https://user-images.githubusercontent.com/11966684/124809440-6a683200-df60-11eb-85e0-52369adb9e51.png)

As for switching emoji “fonts”, this is the feature we support. You can also choose any other emoji style there.
Note that this only applies to the popup of the add-on itself. The add-on does not control how emojis are shown on the website, that is under the website's “authority”.

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
