### ISSUE TITLE
Apple/Google/Twitter/Facebook styles don't display in Thunderbird

### ISSUE THREAD

**Issue by mozomoid** [rugk/awesome-emoji-picker#121]
Hi there!

I just added this extension to my Thunderbird client.
In Options > Appearence, when setting "Emoji style" other than "native", it displays nothing when loaded in TB compose window (see attached screenshot).

Awesome Emoji Picker v0.9
Thunderbird 91.2.1 (32 bits)
Windows 10 Pro x64 21H1

![emoji](https://user-images.githubusercontent.com/37461926/139536035-3416024c-a84a-4c61-baf6-c0908fdf6994.jpg)

**Comment by tdulcet** [comment]
Thanks for the bug report! I can confirm the issue.

@rugk - It looks like there is a separate `scripts/downloadEmojiImages.sh` script that I needed to run to download these images before publishing the add-on on ATN. 🙈 Maybe we would automatically run that from the `scripts/make.sh` script, as I did not catch that I needed to run both of those scripts. Anyway, I am happy to run the script and release a new version on ATN.

**Comment by rugk** [comment]
Oh yes, you do not need to do that. The reason are just size/potential licensing issues, so I don't want to bundle the files all in this repo here.

Feel free to add it there, so the script gets run automatically, yes.

**Comment by tdulcet** [comment]
> Oh yes, you do not need to do that. The reason are just size/potential licensing issues, so I don't want to bundle the files all in this repo here.

OK, I ran the script and released a new v0.9.1 on ATN. This issue can now be closed.

@mozomoid - You could get the update in 24 hours. Thanks again for the bug report!

**Comment by mozomoid** [comment]
Wow that was quick!
I got automatic update to v0.9.1 and everything is fine now.
This add-on is, well... awsome ^^
Thanks to both of you
