### ISSUE TITLE
Alternate Emojis not displayed on Instagram.

### ISSUE THREAD

**Issue by HarleySalas** [rugk/awesome-emoji-picker#123]
Not sure if I'm fully understanding the capability of this plugin, so I apologize if it doesn't fit.

I'm trying to get Apple Emoji's to be displayed on Instagram, so that I can take screenshots of the mobile screen simulation in the Inspect feature.

After installing the plugin, I switched the emoji's to Apple and if I type an emoji in a text field, it does show up as an Apple emoji. However, the pre-existing emojis on a page still remain in the Windows 10 format. If I inspect and try to replace the windows 10 emojis with the copied apple emoji's from the plugin, it simply pastes in as a Windows 10 Emoji. I can't seem to figure out a way to have the Apple emojis displayed instead. I'm under the impression that this plugin is supposed to override/change emojis seen on social media in to the format of your choosing?

Firefox version 96

**Comment by rugk** [comment]
Hi and thanks for your report.

> I'm under the impression that this plugin is supposed to override/change emojis seen on social media in to the format of your choosing?

Unfortunately, I have to say that this impression is wrong. It just inserts the emoji as an Unicode character. What each website or platform/operation system does with that and how it displays it, differs. You can [see a list of all styles e.g. on Emojipedia](https://emojipedia.org/).
The setting for choosing the emoji style only applies to the add-on itself, i.e. how it is shown in the add-on.

I hope this helped to solve your question.
