### ISSUE TITLE
[Thunderbird] No emojis visible after one selcted

### ISSUE THREAD

**Issue by nikolai-nikolajevic** [rugk/awesome-emoji-picker#125]
## Bug description
Emojis not visible after one selected
  

https://user-images.githubusercontent.com/37556958/171581403-ff170018-ad9b-4b99-bb31-7f2094fe187f.mov

## Steps to reproduce

1. Select first emoji
2. Paste it somewhere
3. Open emoji picker

### Actual behavior

Emojis not visible

### Expected behavior

Emojis visible

## System

Operating system and version: Mac mini (M1, 2020) / macOS 12.3
Browser and version: Thunderbird 91.10.0
Add-on version: 0.9.1

## Possible solution

🤷‍♂️

## Miscellaneous

This issue is reproducible on https://missive.github.io/emoji-mart/: No

**Comment by tdulcet** [comment]
@nikolai-nikolajevic - Thanks for the bug report! Unfortunately, I am not able to reproduce this issue, although I do not have access to a Mac. Did you just install the add-on or did the issue recently start occurring? Do the emojis appear after reopening the compose window or restarting Thunderbird? Do you have any other Thunderbird add-ons installed that have a popup?

Similar to https://github.com/rugk/awesome-emoji-picker/issues/49#issuecomment-916967025, this is most likely a Thunderbird/Gecko bug.

**Comment by nikolai-nikolajevic** [comment]
I just installed the add-on and it works (but only one time) when I reopen the compose window. Don't have to restart thunderbird. No more add-ons installed

**Comment by tdulcet** [comment]
Thanks for the additional information. From your video, it looks like you unchecked the "Automatically insert emoji into web page" option (this would likely be localized into your language). Did you change any other options? The add-on looks to be using the dark theme, but the Thunderbird compose window seems to be using the default light theme, so are you using a custom Thunderbird theme?

Would you mind checking the extension's console for any errors after reproducing the issue? Go to the Thunderbird menu "≡", click "🧩 Add-ons and Themes", the "⚙" icon in the upper right, select "Debug Add-ons", find the "Awesome Emoji Picker" in the list and click "Inspect" button, then the "Console" tab. There are screenshots of these steps [here](https://developer.thunderbird.net/add-ons/mailextensions/hello-world-add-on#installing). This should help determine if it is a Thunderbird bug or an issue with the add-on.

**Comment by tdulcet** [comment]
@rugk - I am still waiting for more information from @nikolai-nikolajevic, but as I said above, this is most likely a Thunderbird bug. Someone who is able to reproduce the issue would need to submit a bug on BMO. There are already a few known issues with the Thunderbird popups, including [bug 1733195](https://bugzilla.mozilla.org/show_bug.cgi?id=1733195) and [bug 1716295](https://bugzilla.mozilla.org/show_bug.cgi?id=1716295) (see https://github.com/rugk/awesome-emoji-picker/issues/49#issuecomment-635390352).

**Comment by nikolai-nikolajevic** [comment]
Hi :)

Thats the output of the console. I put some comments to understand what happend 

![emoji-picker-console](https://user-images.githubusercontent.com/37556958/172598289-c2a6bb9b-a6ad-4802-980c-73b52fcf4f9b.png)


Maybe it's the "random tip" error?

**Comment by tdulcet** [comment]
> Thats the output of the console. I put some comments to understand what happend

Thanks for the screenshot and annotations, that is a big help! I do not see any issues with the add-on, so it is almost certainly a Thunderbird bug. If you have a chance, it would be great if you could create a bug on BMO: https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird and let them know it is only reproducible with Thunderbird on macOS.

> Maybe it's the "random tip" error?

No, that is actually not an error, see https://github.com/TinyWebEx/RandomTips/issues/7. Same for those "object is not frozen" warnings: https://github.com/TinyWebEx/AddonSettings/issues/7.
