### ISSUE TITLE
addon breaks composer

### ISSUE THREAD

**Issue by gene-git** [rugk/awesome-emoji-picker#132]
## Bug description
When AEP is active - typing any text in thunderbird composer window and presss ENTER key - an extra unwanted blank line is inserted.
Turn it off and this goes away.

**Comment by tdulcet** [comment]
Duplicate #129.

**Comment by gene-git** [comment]
missed that - indeed its the same bug

**Comment by rugk** [comment]
Duplicate of https://github.com/rugk/awesome-emoji-picker/issues/129
