### ISSUE TITLE
Be able to disable "Searching for emojis [...] is disabled" in address/search bar

### ISSUE THREAD

**Issue by Exagone313** [rugk/awesome-emoji-picker#139]
## Background

When I try to search for keywords starting by `emoji` and press enter, it redirects me to this addon preferences and I loose my search keywords. My current workaround is to never put emoji as a first keyword, which is not desired (since the first keyword usually has a greater weight in search engines).

![22-10-05-11-11-05-414725361](https://user-images.githubusercontent.com/11819703/194025591-d261d87b-5c69-4004-82be-70bd6990d86b.png)

## Proposed solution

Do not ask to enable this option when it is disabled.

## Alternatives

* Add an option to disable this behavior in the preferences
* Only ask to enable it the first time

## Additional context

Integration is disabled:

![22-10-05-11-15-11-703704373](https://user-images.githubusercontent.com/11819703/194025579-5155da37-4af2-49d8-bf58-c5501415cc07.png)

**Comment by tdulcet** [comment]
> In my case I could report this as a bug to Firefox, since I already entered a keyword (for a search engine).

Yeah, I would agree that this is a Firefox bug, as users should not be able to use multiple keywords at once. Please do report it to them if you can.

> the keyword that triggers the search needs to be statically defined

See [bug 1375453](https://bugzilla.mozilla.org/show_bug.cgi?id=1375453) for allowing the user to change the keyword. There are actually a lot of known issues with this feature, including that it does not work in private windows ([bug 1779400](https://bugzilla.mozilla.org/show_bug.cgi?id=1779400)) and it can only show a fixed number of suggestions ([bug 1375252](https://bugzilla.mozilla.org/show_bug.cgi?id=1375252)).

**Comment by rugk** [comment]
> Yeah, I would agree that this is a Firefox bug, as users should not be able to use multiple keywords at once. Please do report it to them if you can.

Did you find the time to do this, @Exagone313? I totally agree, multiple keywords is not really useful/should not be possible.

**Comment by Exagone313** [comment]
> Did you find the time to do this, @Exagone313?

I didn't, but thanks for reminding me. 😅

**Comment by hockdudu** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1815819 was fixed. This doesn't solve our issue completely, but the suggestion doesn't come anymore when the search is prefixed with `@google` or `?`.

**Comment by Exagone313** [comment]
Personally, I think the issue is now fixed in Firefox 130.

> This doesn't solve our issue completely

@hockdudu What do you think still need to be fixed?

**Comment by rugk** [comment]
Okay https://hg.mozilla.org/mozilla-central/rev/e0b29efee642 reads like you can now at least not do enter two keywords at once.

More could be done [like allowing users to change they keyword](https://bugzilla.mozilla.org/show_bug.cgi?id=1375453). You could then change it to anything else to not let it interfere with whatever you type in the omnibox.

**Comment by Exagone313** [comment]
I think this needs a separate issue. I'm closing the present one, but feel free to re-open it if you think something else is missing.
