### ISSUE TITLE
Please add lungs 🫁 

### ISSUE THREAD

**Issue by mcfdg** [rugk/awesome-emoji-picker#141]

**Comment by rugk** [comment]
https://emojipedia.org/lungs/

> Lungs was approved as part of [Unicode 13.0](https://emojipedia.org/unicode-13.0/) in 2020 and added to [Emoji 13.0](https://emojipedia.org/emoji-13.0/) in 2020.

We unfortunately still have an older version of that, so unfortunately blocked/a duplicate of https://github.com/rugk/awesome-emoji-picker/issues/116.

This should be in there when the next version is released.

**Comment by rugk** [comment]
Duplicate of https://github.com/rugk/awesome-emoji-picker/issues/116
