### ISSUE TITLE
Add emoji selector to context menu (right click menu)

### ISSUE THREAD

**Issue by JakeShirley** [rugk/awesome-emoji-picker#144]
## Background

In Edge you can right click and select an emoji easily just with the mouse.  I'd love to be able to do that with this extension as well!

## Proposed solution

Here are a few photos of how Edge does it:

![image](https://github.com/rugk/awesome-emoji-picker/assets/1000311/9f819f54-47cf-4b94-a68f-a89745509206)

![image](https://github.com/rugk/awesome-emoji-picker/assets/1000311/d219c43e-fd99-44d2-9e1f-3f4cbdcbbc3f)

**Comment by rugk** [comment]
This has already been implemented with https://github.com/rugk/awesome-emoji-picker/pull/137 and as such is already implemented. It will open the usual emoji picker, but it kinda works. It is [just not released yet](https://github.com/rugk/awesome-emoji-picker/compare/v2.0...main).
