### ISSUE TITLE
Add-on settings should support dark mode

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#23]
See https://github.com/rugk/offline-qr-code/issues/190

![image](https://user-images.githubusercontent.com/11966684/56851696-2bff7300-6912-11e9-87c2-89826134776e.png)

**Comment by Prometheos2** [comment]
Personally, none of my add-on support this feature.
Heck, even Firefox Developer's add-on "page" doesn't supply me with one.

**Comment by rugk** [comment]
>  none of my add-on support this feature.

Yes, because this is really a new feature and the add-ons page is only dark in Firefox Nightly in such a case. So I am just tracking this change very early. Nothing to worry yet… :wink:

**Comment by lionirdeadman** [comment]
Would be nice if the pop-up did too.

**Comment by rugk** [comment]
Fair enough, indeed, opened diffenet issue though: https://github.com/rugk/awesome-emoji-picker/issues/47
