### ISSUE TITLE
Opening via hot key prevents it from focusing input

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#28]
## STR

1. Ctrl+Shift+Period

## What happens

Input field not focused

![image](https://user-images.githubusercontent.com/11966684/57197414-61860b00-6f67-11e9-81bd-d99a4bf205c4.png)

## What should happen

Auto-focus should work.

## System

Firefox 66
Linux/GNOME/Fedora 30

**Comment by Prometheos2** [comment]
I had a similar bug when clicking on the icon, but I can't reproduce it in a manner to understand the problem.

**Comment by rugk** [comment]
What do you refer when saying "application"? The add-on?

If so, yeah, it may be some focus problem, I am not sure. AFAIK this happens on all OSes, but when opening this issue I saw it on Linux/GNOME.

BTW also asked in the Mozilla forum, but there are also not many people, who know what causes this: https://discourse.mozilla.org/t/firefox-internals-what-technically-differenciates-a-hot-key-command-popup-opening-from-click-opening/40307?u=rugkx

---

In any way, one could implement a workaround to constantly re-try (manually) focusing the input field. I've done something similar in my Offline QR Code Generator add-on here:
https://github.com/rugk/offline-qr-code/blob/e900c8878f86f2b3bea5558b686097b766fa9cba/src/popup/modules/UserInterface.js#L132-L165

Obviously, this would be a workaround, because the feature from emoji-mart just does not work… :thinking: 
(But I also cannot report it to emoji-mart, because I don't know what exactly causes this issue.)

**Comment by rugk** [comment]
BTW Firefox seems top have fixed this, at least even when removing my workaround, I cannot reproduce it in Firefox 74.
