### ISSUE TITLE
Messenger blocked when using Facebook's instantaneous messages

### ISSUE THREAD

**Issue by Prometheos2** [rugk/awesome-emoji-picker#37]
Trying to insert an emoji in the instantaneous messages results in the blockage of the Messenger in the current page.

It only does that bug when no character are into the dialog box beforehand. 

I assume it's on Fb's side, like an non-handled error or an anti-bot/flood/spam measure; so it might be hard to fix that.
I'm not sure we can access the message field to determine whether or not the field is empty through the add-on.

**Comment by rugk** [comment]
Thanks for the report. Yes, it's likely specific to that site.
Maybe they don't even have a real input field when there is no character entered yet.

Anyway, there is indeed hardly anything I can do. But good that it's tracked. Just as the [other site issues](https://github.com/rugk/awesome-emoji-picker/labels/site-issue).

**Comment by Prometheos2** [comment]
Would it be possible to detect when the cursor is in the Messenger "box" and block the emoji insertion?

Or, if that _is_ the problem, detecting a loss of focus from the Messenger box when the add-on dialog box opens?

**Comment by rugk** [comment]
Anything is possible, but this sounds like a very specific cumbersome workaround (which does not even actually fix the problem of insertion, just prevent bad side effects). Though it may be worth it for such a big site.

I am not completly oppoosed to it, but it has to be well-thought. E.g. make it such generic that one can later add similar/other workarounds for other sites.
That said, I'd appreciate concrete development ideas or even pull requests on that feature. 😃 

Also, BTW, do you have a screenshot on how that "blockage" looks like?

**Comment by Prometheos2** [comment]
"That said, I'd appreciate concrete development ideas or even pull requests on that feature. 😃"
Oh no 😥

Well, it's complicated, since it's more about not being able to reopen some dialog rather than something more "screenshot-able"

I will send you the JS console logs instead

**Comment by Prometheos2** [comment]
[console-export-2019-9-19_18-40-39.txt](https://github.com/rugk/awesome-emoji-picker/files/3632328/console-export-2019-9-19_18-40-39.txt)

**Comment by rugk** [comment]
Hmm, okay, I don't see any error related to this bug/add-on or so.

> Is "browser-polyfill.min.js" your thing?

No, that has to be a different add-on. You can look up the add-on ID in `about:debugging`.

**Comment by Prometheos2** [comment]
That's weird, then.
It would truly be on Fb's side?
_____

> No, that has to be a different add-on.
I've checked, and yes, it's another extension.
It probably attempts to access the (now-crashed) message box.

QA is hard ^^

**Comment by Prometheos2** [comment]
Addendum: It also concerns the Messenger page itself, as it blocks the text area until refreshment (cf. screenshot & JS console extract), but the emoji is inserted and can be seen on refresh.

_______

### Screenshot
![image](https://user-images.githubusercontent.com/45640841/70217558-aeba9d00-1741-11ea-988c-e9bc218dc5db.png)

### JS Console extracts
`
ErrorUtils caught an error: "React reported an error from NotFoundError: Node was not found". Subsequent errors won't be logged; see https://fburl.com/debugjs. 8gEnQK1P6Dl.js:51:246
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://660ce86a-a063-4dab-8aea-184db93e38bb/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map
`

[extended JS console extract.txt](https://github.com/rugk/awesome-emoji-picker/files/3925771/extended.JS.console.extract.txt)

**Comment by Prometheos2** [comment]
With the new version of the website, the issue seems to be solved.

However, like in !38, inserting two (or more) emojis results in very awkward events.
That's hard to pinpoint what it gives

**Comment by rugk** [comment]
Okay, so if this problem is fixed, that's good, please open a new issue.

If the other issue is really the same as https://github.com/rugk/awesome-emoji-picker/issues/38, we could expand https://github.com/rugk/awesome-emoji-picker/issues/38 to also track the Messenger problem, but this one here seems fixed so I'm closing this.
