### ISSUE TITLE
Automatically adjust width in overflow menu & Android

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#42]
We don't want that:
![image](https://user-images.githubusercontent.com/11966684/58713550-1672e280-83c3-11e9-8087-8aa72bbb97cc.png)

…or the same on Android, where we have a fixed witdh.

## Solution

Thus, we should ignore the user setting of the width there and just set `width: auto`, which lets emoji-mart use all width it has.
Maybe the same for height?

## TODO

* [x] As we may also need this in OfflineQr, for https://github.com/rugk/offline-qr-code/issues/187, make a common lib to determinate where a page is running.
* [x] implement this issue here based on that lib

**Comment by nclm** [comment]
I was going to post this. I do have the opposite, where the picker is smaller than the overflow menu:

![before](https://user-images.githubusercontent.com/923008/59565319-360c3b00-9052-11e9-9d06-10fb4f9681dc.png)

(I temporarily fixed it by choosing ‘11’ columns in the preferences, but it should be automatic)

**Comment by rugk** [comment]
BTW common lib is in development: https://github.com/TinyWebEx/EnvironmentDetector
