### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by lionirdeadman** [rugk/awesome-emoji-picker#45]
## Background

I think adding a context menu would be closer to what you type meaning there's less movement involved to activate it and it means I can have one less icon on the top bar. :wink: 

## Proposed solution

Add context menu functionality

**Comment by rugk** [comment]
You know you can also use a hot key? (Did not you?)

Considering this hot key feature and the fact that you are likely actively typing when you want to insert an emoji, is not a hot key faster/more convenient/… to use?
What would justify another menu entry in such a case? (I mean, I just don't want to bloat people's context menu (unnecessarily)… that grows very fast if you have many add-ons.)

**Comment by lionirdeadman** [comment]
I didn't actually but is it possible to make the emoji picker closer to the text? The purpose of the context menu in my mind was to *not* drag my mouse over there. (It also doesn't work if you remove the icon from the bar) 🤔

**Comment by rugk** [comment]
> It also doesn't work if you remove the icon from the bar

Put it into the overflow menu, then it should work at least. But if it is really hidden, yes, it obviously does not work. (BTW if you don't know: You can disabled the colored icon in the settings. Then it does not disturb so much, at least. :wink: Did you know that?)

> I didn't actually but is it possible to make the emoji picker closer to the text?

https://github.com/rugk/awesome-emoji-picker/issues/9 should cover this.

**Comment by lionirdeadman** [comment]
>(BTW if you don't know: You can disabled the colored icon in the settings. Then it does not disturb so much, at least. wink Did you know that?)

I did and it fits nicely there but.. I'm rather conservative with what I put there 😉

>#9 should cover this.

I see, I'll subscribe to the issue and close this then. 🙏

**Comment by rugk** [comment]
Yeah, that said, maybe there are anyway arguments in favor of a context menu (instead of only hot key) for the emoji picker. If anyone thinks so, feel free to comment here.

**Comment by lionirdeadman** [comment]
I mean, I know GNOME's emoji picker has both so there's a precedent for that behaviour. If you're worried that it might be unwanted, it could be an extension setting if possible.

**Comment by rugk** [comment]
Hmm, so keeping it open for visibility…
