### ISSUE TITLE
Chrome/ium support

### ISSUE THREAD

**Issue by Kaligula0** [rugk/awesome-emoji-picker#54]
Is there any chance that your awesome emoji picker will become available for Chrome surfers?

**Comment by rugk** [comment]
Theoretically, I have nothing against it. See https://github.com/rugk/offline-qr-code/issues/59 for the reasoning on whether/how a Chrome/ium version could be made available. The TL;DR is: The code base must keep supporting the new WebExtension (extension) API of Firefox, but we can include polyfills in the Chrome/ium version. Whether all features really work is not clear. (e.g. popup opening is a problem, as you can read there)

Also tagging this as "help wanted" as I currently won't do any work on it and focus on other things. If anyone wants to take this up/contribute, feel free to do so. Everything I wrote in https://github.com/rugk/offline-qr-code/issues/59 applies.
