### ISSUE TITLE
Automatically insert into active page

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#6]
…instead of copying.

As an option, however.

**Comment by Prometheos2** [comment]
I know [Johannhof's **emoji-helper**](https://github.com/johannhof/emoji-helper) project (_A.K.A._ the **Emoji Cheatsheet** add-on) tried to do that, but to no avail (to my knowledge).

**Comment by rugk** [comment]
It's possible. Actually, I am already working on it and you can test it in https://github.com/rugk/awesome-emoji-picker/issues/7.

**Comment by rugk** [comment]
Oh, sorry, wrong link, I meant https://github.com/rugk/awesome-emoji-picker/pull/10 and it is actually fixed/merged now… :smiley:
