### ISSUE TITLE
Wrong icon until refreshment.

### ISSUE THREAD

**Issue by Prometheos2** [rugk/awesome-emoji-picker#75]
## Bug description

The wrong add-on icon appears, despite the parameters.

## Steps to reproduce

Currently unknown.

### Actual behavior

The transparent add-on icon in the toolbar appears instead of the colored one (🤩).

Disabling and re-enabling the icon parameter seems to revert the problem temporarily.

### Expected behavior

Having the icon corresponding to the selected parameter.

## System

Operating system and version: 
Browser and version: Firefox 
Add-on version: 1.2 (January 15, 2020)

## Possible solution

The problem seems to have been created in recent versions since it wasn't there before (for me).

**Comment by rugk** [comment]
Reproduced. Just opening the settings page also fixes it.

Likely an issue in the init code or so.

Okay found the issue, seems I accidentially deleted the whole icon handler taht sets the icon on startup. [This is](https://github.com/rugk/offline-qr-code/blob/8e8df9c84bc6eb81da906fb5db19f102a6049a50/src/background/background.js#L8) how it's supposed to be.
