### ISSUE TITLE
Rename EmojiOne to JoyPixels in the dropdown?

### ISSUE THREAD

**Issue by dmxt** [rugk/awesome-emoji-picker#82]
For skimmers: just bold text is important

## Bug description
**Set emoji-style dropdown (in the Firefox add-on option page) still have 'EmojiOne' as an option.**

**Wouldn't it be reasonable to rename EmojiOne to JoyPixels in the dropdown too?**

EmojiOne recently got renamed to JoyPixels (referring to the README)

## Steps to reproduce

1. Open the Firefox add-on option page
2. Click 'set' dropdown
3. Examine the emoji name 'EmojiOne'

### Actual behavior
Witness the name EmojiOne in the dropdown

### Expected behavior
Witness the name JoyPixels in the dropdown

## System
Operating system and version: Arch Linux x86_64 why? Btw the kernel is 5.57-arch1-1 
**Browser and version: Firefox 73.0.1 (64-bit)**
**Add-on version: 1.2 (last updated January 21, 2020)**

## Possible solution
**Rename EmojiOne to JoyPixels in the dropdown**

### Footnote:
Some humor was included bc of answering the template questions for something trivial lol

**Comment by rugk** [comment]
Hehe, well... in such an obvious case you could have skipped the non-essential parts of the template. 😄 

Anyway, yes, that would be an idea. Actually, the included Emojis, however, still _are_ the ones from EmojiOne, i.e. the old ones before it was renamed. That is due to legal reasons and the upstream, projects already have removed it, see https://github.com/iamcal/emoji-data/pull/142.

**Comment by rugk** [comment]
I just saw I have no issue for discussion EmojiOne/JoyPixels support in the future, so here is one: https://github.com/rugk/awesome-emoji-picker/issues/83

**Comment by dmxt** [comment]
> I just saw I have no issue for discussion EmojiOne/JoyPixels support in the future, so here is one: #83


It's a little embarrassing I can't understand PR, I'm a UX/UI designer, who was trying hard to practice code to no avail although.¹ 

Could you explain to me what's going on?

---

¹ I wish I can learn JS, but lack of help has been holding me back because it's not only JS, it's the programming language I do not know how to approach and figure out how to solve problems, I know syntaxes, but I don't know how to write a program. :)

**Comment by rugk** [comment]
So emoji-mart v3.0.0 has been integrated here, [which removes EmojiOne support](https://github.com/missive/emoji-mart/blob/master/CHANGELOG.md#v300). Closing this here then, as there is nothing to do now, anymore.

Unfortunately: :man_shrugging: :cry:

I stay interesting in potentially going through some legal hooks to get support back or so, but please follow https://github.com/rugk/awesome-emoji-picker/issues/83 for that.
