### ISSUE TITLE
Convert contributors file to markdown file

### ISSUE THREAD

**Issue by rugk** [rugk/awesome-emoji-picker#87]
so it looks better… :smile: 

/cc @Prometheos2 you seem to wanted to do that already in https://github.com/rugk/awesome-emoji-picker/pull/26#pullrequestreview-233770997-body-html

If you want to do it before the v2.0 release now then here is your chance… :stuck_out_tongue_winking_eye:

**Comment by Prometheos2** [comment]
Sorry, I'm a bit short on time currently. When do you plan on releasing it? I could try to work on it.

**Comment by rugk** [comment]
@Prometheos2 The plan is [today](https://github.com/rugk/awesome-emoji-picker/milestone/5), see [the translation notification issue](https://github.com/rugk/awesome-emoji-picker/issues/27#issuecomment-601797142) (did not you got a notification for this?), but well, if you want to fix it quickly in the next days, I could also delay that a bit… :wink: 
I guess more important for v2.0 are [the translation](https://github.com/rugk/awesome-emoji-picker/issues/27#issuecomment-601797142), as mentioned before.

**Comment by Prometheos2** [comment]
I missed the info on the issue, my bad.

I will do the translations
