### ISSUE TITLE
Firefox 77 breaks popup positioning

### ISSUE THREAD

**Issue by apiraino** [rugk/awesome-emoji-picker#92]
## Bug description
The popup opens outside the browser window. If the browser if at edge of the screen the popup is not visible.

## Steps to reproduce
Not 100% sure but I think it started after updating to Firefox 77 early betas :-)

## System
Ubuntu running Wayland and Sway window manager

Operating system and version: Ubuntu 19.10
Browser and version: Firefox 77 beta 
Add-on version: 2.0

## Miscellaneous

This issue is reproducible on https://missive.github.io/emoji-mart/: Yes

![2020-05-06_15:31:22](https://user-images.githubusercontent.com/6098822/81183936-13f41200-8fb0-11ea-9a50-c9a6ec9c0483.png)

**Comment by rugk** [comment]
> This issue is reproducible on https://missive.github.io/emoji-mart/: Yes

Huhb? How exactly. There is no popup…
I mean, I mean the emoji picker there.

Anyway, 1. that Firefox is still beta and 2. it is likely a Firefox issue.

I'd suggest you to test whether the same works with other add-ons/popups.
And then do report this as a bug on https://bugzilla.mozilla.org/ to Mozilla.

If more technical information are needed: This add-on uses React (preact) and thus the popup at first has a small size (2x2px or so) and when the JS finishes it's loading, it is resized. This _may_ be a reason, if it is not reproducible with other add-ons.
(If you want to check that/test it, you can try changing the "emojis per line" size in the settings, which influences the width. So if this influences the position of the popup, that may be a reason triggering the bug.)

BTW, I've seen similar Wayland issues before, but as of FF 57 I did not saw it for a long time. Anyway, it's likely a valid issue.

**Comment by apiraino** [comment]
Thanks for the tech details and sorry for my poor language. The emoji picker is clearly the "popup I was referring to. And, yes, clearly this is "youth issue" of FF77 (sorry I didnt stress enough this point). This is also reflected by the erratic behaviour when the emoji picker opens: I've noticed that _sometimes_ it opens in the expected position.

This issue was meant to track this behaviour until FF77 is stabilized.

**Comment by apiraino** [comment]
Opened an issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1636943
